"""Interactive first-time setup wizard.

Walks internal staff through environment checks, credential setup
(NyxID preferred, env-var fallback), Playwright + Chromium install,
and per-platform first-time login. Idempotent: re-running reports
"already configured" for completed steps and only re-triggers logins
when the user explicitly asks.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import typer


STATE_DIR = Path("state")
ENV_PATH = STATE_DIR / ".env"
STEP_KEYS = ("env", "llm", "douyin", "xhs", "notebooklm")
PROVIDER_CHOICES = ("openai", "anthropic", "ollama")
TIER_CHOICES = ("tier1", "tier2", "tier3")
PLATFORM_CHOICES = ("douyin", "xhs", "x")
DEFAULT_MODELS = {
    "openai": "gpt-4o-mini",
    "anthropic": "claude-haiku-4-5-20251001",
    "ollama": "llama3.3:70b",
}


def _read_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def _write_env(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# Generated by `broadcast-kit setup` on {datetime.now(timezone.utc).date().isoformat()}. Edit by hand if needed."]
    for k, v in values.items():
        lines.append(f"{k}={v}")
    lines.append("# Optional:")
    lines.append("# BITGRIT_API_KEY=...")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def _ask(prompt: str, default: str | None, yes: bool) -> str:
    if yes:
        return default or ""
    return typer.prompt(prompt, default=default) if default is not None else typer.prompt(prompt)


def _confirm(prompt: str, default: bool, yes: bool) -> bool:
    if yes:
        return default
    return typer.confirm(prompt, default=default)


def _check_env(minimal: bool = False) -> dict:
    """Probe local environment. When minimal=True, only Python is checked
    (used by `--for tier1` when no platform-specific dependencies are needed)."""
    checks: dict = {}
    checks["python"] = {"ok": sys.version_info >= (3, 11), "version": f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"}
    if minimal:
        return checks
    checks["ffmpeg"] = {"ok": shutil.which("ffmpeg") is not None, "path": shutil.which("ffmpeg")}
    try:
        import playwright  # noqa: F401
        checks["playwright"] = {"ok": True}
    except ImportError:
        checks["playwright"] = {"ok": False}
    cache = Path.home() / "Library/Caches/ms-playwright"
    chromium_installed = False
    if cache.exists():
        chromium_installed = any(p.name.startswith("chromium") for p in cache.iterdir())
    else:
        linux_cache = Path.home() / ".cache/ms-playwright"
        if linux_cache.exists():
            chromium_installed = any(p.name.startswith("chromium") for p in linux_cache.iterdir())
    checks["chromium"] = {"ok": chromium_installed}
    return checks


def _maybe_install_playwright(checks: dict, yes: bool) -> None:
    if not checks["playwright"]["ok"]:
        if _confirm("playwright Python package is missing — install via pip now?", default=True, yes=yes):
            subprocess.run([sys.executable, "-m", "pip", "install", "playwright>=1.43"], check=False)
            try:
                import playwright  # noqa: F401
                checks["playwright"]["ok"] = True
            except ImportError:
                pass
    if checks["playwright"]["ok"] and not checks["chromium"]["ok"]:
        if _confirm("Chromium browser is not installed — run `playwright install chromium` now?", default=True, yes=yes):
            subprocess.run([sys.executable, "-m", "playwright", "install", "chromium"], check=False)
            checks["chromium"]["ok"] = True


def _nyxid_available() -> bool:
    return shutil.which("nyxid") is not None


def _nyxid_services() -> list[str]:
    try:
        result = subprocess.run(["nyxid", "status", "--json"], capture_output=True, text=True, timeout=10)
        if result.returncode != 0:
            return []
        data = json.loads(result.stdout)
        services = data.get("services") or data.get("nodes") or []
        if isinstance(services, list):
            return [str(s.get("service") or s.get("name") or s) for s in services if s]
        return []
    except (subprocess.SubprocessError, json.JSONDecodeError, OSError):
        return []


def _step_llm(env: dict[str, str], yes: bool, reset: bool) -> dict:
    if not reset and env.get("BROADCAST_KIT_LLM_PROVIDER") and (
        env.get("OPENAI_API_KEY") or env.get("ANTHROPIC_API_KEY") or env.get("OLLAMA_BASE_URL")
        or env.get("BROADCAST_KIT_LLM_PROVIDER") == "ollama"
    ):
        return {"ok": True, "status": "already configured", "provider": env["BROADCAST_KIT_LLM_PROVIDER"]}

    use_nyxid = _confirm("Use NyxID broker for LLM credentials (recommended for internal staff)?", default=True, yes=yes)
    provider_default = env.get("BROADCAST_KIT_LLM_PROVIDER", "anthropic")

    if use_nyxid:
        if not _nyxid_available():
            typer.echo("nyxid CLI not on PATH. Install with: pip install nyxid-cli  (or see internal docs).")
            return {"ok": False, "status": "nyxid missing", "hint": "install nyxid CLI then re-run setup"}
        services = _nyxid_services()
        typer.echo(f"nyxid services available: {', '.join(services) if services else '(none)'}")
        provider = _ask("LLM provider (openai/anthropic/ollama)", provider_default, yes)
        if provider not in PROVIDER_CHOICES:
            return {"ok": False, "status": f"invalid provider: {provider}"}
        if provider in ("openai", "anthropic") and provider not in services:
            typer.echo(f"Provider {provider!r} not registered with NyxID. Run: nyxid add {provider}")
            typer.echo("(staff completes auth in the browser; then re-run `broadcast-kit setup`)")
            return {"ok": False, "status": f"nyxid {provider} not registered"}
        model = _ask("Model id", DEFAULT_MODELS[provider], yes)
        env["BROADCAST_KIT_LLM_PROVIDER"] = provider
        env["BROADCAST_KIT_LLM_MODEL"] = model
        env["BROADCAST_KIT_LLM_CRED_SOURCE"] = "nyxid"
        _write_env(ENV_PATH, env)
        return {"ok": True, "status": "configured via nyxid", "provider": provider, "model": model}

    provider = _ask("LLM provider (openai/anthropic/ollama)", provider_default, yes)
    if provider not in PROVIDER_CHOICES:
        return {"ok": False, "status": f"invalid provider: {provider}"}
    model = _ask("Model id", DEFAULT_MODELS[provider], yes)
    env["BROADCAST_KIT_LLM_PROVIDER"] = provider
    env["BROADCAST_KIT_LLM_MODEL"] = model
    env["BROADCAST_KIT_LLM_CRED_SOURCE"] = "env"
    if provider == "openai":
        key = env.get("OPENAI_API_KEY") or (typer.prompt("OPENAI_API_KEY", hide_input=True) if not yes else "")
        if key:
            env["OPENAI_API_KEY"] = key
    elif provider == "anthropic":
        key = env.get("ANTHROPIC_API_KEY") or (typer.prompt("ANTHROPIC_API_KEY", hide_input=True) if not yes else "")
        if key:
            env["ANTHROPIC_API_KEY"] = key
    elif provider == "ollama":
        env["OLLAMA_BASE_URL"] = env.get("OLLAMA_BASE_URL") or _ask("OLLAMA_BASE_URL", "http://localhost:11434", yes)
    _write_env(ENV_PATH, env)
    return {"ok": True, "status": "configured via env", "provider": provider, "model": model}


def _step_login(platform: str, yes: bool) -> dict:
    if not _confirm(f"Run first-time login for {platform} now? (opens Chromium)", default=False, yes=yes):
        return {"ok": True, "status": "skipped by user"}
    cmd = [sys.executable, "-m", f"broadcast_kit.publishers.{platform}.cli", "login", "--fresh"]
    try:
        rc = subprocess.call(cmd)
        return {"ok": rc == 0, "status": "login completed" if rc == 0 else f"login exit={rc}"}
    except OSError as exc:
        return {"ok": False, "status": f"login failed: {exc}"}


def _step_notebooklm(yes: bool) -> dict:
    if shutil.which("notebooklm") is None:
        if _confirm("notebooklm CLI missing — install notebooklm-py via pip now?", default=True, yes=yes):
            subprocess.run([sys.executable, "-m", "pip", "install", "notebooklm-py"], check=False)
        if shutil.which("notebooklm") is None:
            typer.echo("notebooklm still not on PATH. Install manually: pip install notebooklm-py && notebooklm login")
            return {"ok": False, "status": "not installed", "hint": "pip install notebooklm-py"}
    if _confirm("Run `notebooklm login` now?", default=False, yes=yes):
        rc = subprocess.call(["notebooklm", "login"])
        return {"ok": rc == 0, "status": "login completed" if rc == 0 else f"login exit={rc}"}
    return {"ok": True, "status": "skipped by user"}


def _step_slidesync() -> dict:
    """Read-only check for the slidesync CLI on PATH. Tier 3 needs it for source-to-video."""
    path = shutil.which("slidesync")
    if path is None:
        return {"ok": False, "status": "not on PATH", "hint": "install slidesync (see external docs); not a pip package"}
    return {"ok": True, "status": "available", "path": path}


def _step_publish_registry(env: dict[str, str], yes: bool, reset: bool) -> dict:
    """Tier 2: locate the user's publish-registry.json and stash its path in state/.env."""
    existing = env.get("PUBLISH_REGISTRY_PATH")
    if existing and not reset and Path(existing).exists():
        return {"ok": True, "status": "already configured", "path": existing}

    default = existing or "state/publish-registry.json"
    raw = _ask("Path to publish-registry.json", default, yes)
    if not raw:
        return {"ok": False, "status": "no path provided"}
    path = Path(raw).expanduser()
    if not path.exists():
        return {"ok": False, "status": f"file not found: {path}", "hint": "create it or pass a valid path"}

    validation: dict = {"status": "exists"}
    try:
        with path.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, json.JSONDecodeError) as exc:
        return {"ok": False, "status": f"unreadable json: {exc}", "path": str(path)}

    schema_path = Path("contracts/publish-registry.schema.json")
    try:
        import jsonschema  # type: ignore
        if schema_path.exists():
            with schema_path.open("r", encoding="utf-8") as fh:
                schema = json.load(fh)
            try:
                jsonschema.validate(data, schema)
                validation = {"status": "validated against schema"}
            except jsonschema.ValidationError as exc:  # type: ignore[attr-defined]
                return {
                    "ok": False,
                    "status": f"schema validation failed: {exc.message}",
                    "path": str(path),
                }
        else:
            validation = {"status": "schema file missing; only existence checked"}
    except ImportError:
        validation = {"status": "jsonschema not installed; only existence checked"}

    env["PUBLISH_REGISTRY_PATH"] = str(path.resolve())
    _write_env(ENV_PATH, env)
    return {"ok": True, "status": validation["status"], "path": str(path.resolve())}


def _ask_platforms(yes: bool) -> list[str]:
    """Ask the user which platforms they actually plan to publish to. Tier mode only."""
    if yes:
        return list(PLATFORM_CHOICES)
    raw = typer.prompt(
        f"Which platforms? Comma-separated from {', '.join(PLATFORM_CHOICES)}",
        default=",".join(PLATFORM_CHOICES),
    )
    chosen = [p.strip() for p in raw.split(",") if p.strip()]
    return [p for p in chosen if p in PLATFORM_CHOICES]


def _doctor_summary() -> dict | None:
    """Re-run doctor (read-only) to surface which tiers the host can now serve."""
    try:
        from broadcast_kit.commands import doctor as _doctor
        report = _doctor.run(live_login_check=False)
        return report.get("summary") if isinstance(report, dict) else None
    except Exception:  # noqa: BLE001
        return None


def run(
    yes: bool = False,
    skip: list[str] | None = None,
    reset: bool = False,
    tier: str | None = None,
) -> dict:
    """Run the wizard.

    Args:
        yes: auto-accept every prompt with the default value.
        skip: step keys to skip (env, llm, douyin, xhs, notebooklm). Independent of `tier`.
        reset: re-ask questions even if state/.env already has answers.
        tier: restrict the wizard to a capability tier (tier1/tier2/tier3). When None,
              run the full legacy flow (backward compatible). When set, only the steps
              required for that tier are run; other steps are not touched (idempotent —
              re-running with a smaller tier never undoes a larger tier).

    Returns the same result-dict shape regardless of tier.
    """
    if tier is not None and tier not in TIER_CHOICES:
        raise ValueError(f"tier must be one of {TIER_CHOICES} or None, got {tier!r}")
    skipped = set(skip or [])
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    env = {} if reset else _read_env(ENV_PATH)
    result: dict = {
        "steps": {},
        "state_dir": str(STATE_DIR.resolve()),
        "env_file": str(ENV_PATH.resolve()),
        "tier": tier,
    }

    # Resolve which platforms to ask about and whether each optional step runs.
    if tier is None:
        platforms = ["douyin", "xhs"]
        run_notebooklm = True
        run_slidesync = False
        run_publish_registry = False
        env_minimal = False
    else:
        platforms = _ask_platforms(yes)
        result["platforms_selected"] = platforms
        # Tier 1 only needs ffmpeg/playwright if a Playwright platform was chosen.
        needs_browser = any(p in {"douyin", "xhs"} for p in platforms)
        env_minimal = not needs_browser
        run_notebooklm = tier == "tier3"
        run_slidesync = tier == "tier3"
        run_publish_registry = tier == "tier2"

    # Step 1: env checks
    if "env" in skipped:
        result["steps"]["env"] = {"ok": True, "status": "skipped"}
    else:
        checks = _check_env(minimal=env_minimal)
        typer.echo("Environment checks:")
        for name, info in checks.items():
            mark = "[ok]" if info["ok"] else "[!!]"
            typer.echo(f"  {mark} {name}: {info}")
        if not env_minimal:
            _maybe_install_playwright(checks, yes)
        result["steps"]["env"] = {"ok": all(c["ok"] for c in checks.values()), "checks": checks}

    # Step 2: LLM credentials
    if "llm" in skipped:
        result["steps"]["llm"] = {"ok": True, "status": "skipped"}
    else:
        result["steps"]["llm"] = _step_llm(env, yes, reset)

    # Step 3: per-platform login
    for platform in platforms:
        if platform in skipped:
            result["steps"][platform] = {"ok": True, "status": "skipped"}
        else:
            result["steps"][platform] = _step_login(platform, yes)

    # Step 4 (tier-gated): NotebookLM. Legacy default runs it; tier1/tier2 skip it.
    if run_notebooklm and "notebooklm" not in skipped:
        result["steps"]["notebooklm"] = _step_notebooklm(yes)
    elif "notebooklm" in skipped:
        result["steps"]["notebooklm"] = {"ok": True, "status": "skipped"}
    # else: tier1/tier2 — leave key absent so we don't claim it was checked.

    # Step 4b (tier3): slidesync presence check (read-only).
    if run_slidesync:
        result["steps"]["slidesync"] = _step_slidesync()

    # Step 4c (tier2): publish-registry path + validation.
    if run_publish_registry:
        result["steps"]["publish_registry"] = _step_publish_registry(env, yes, reset)

    # Step 5: summary
    typer.echo("")
    typer.echo(f"Setup completed for tier: {tier or 'full'}")
    typer.echo("Setup summary:")
    for key, info in result["steps"].items():
        mark = "[ok]" if info.get("ok") else "[!!]"
        typer.echo(f"  {mark} {key}: {info.get('status', '')}")
    typer.echo("")
    typer.echo(f"State dir: {result['state_dir']}")
    typer.echo(f"Env file:  {result['env_file']}")
    summary = _doctor_summary()
    if summary is not None:
        result["doctor_summary"] = summary
        ready = []
        if summary.get("ok_for_douyin_existing_media") or summary.get("ok_for_xhs_existing_media"):
            ready.append("tier1")
        if summary.get("ok_for_douyin_existing_media") or summary.get("ok_for_xhs_existing_media"):
            # tier2 needs the same publishing capability plus a registry path on disk.
            if env.get("PUBLISH_REGISTRY_PATH") and Path(env["PUBLISH_REGISTRY_PATH"]).exists():
                ready.append("tier2")
        if summary.get("ok_for_source_to_video"):
            ready.append("tier3")
        typer.echo(f"Host ready for: {', '.join(ready) if ready else '(none yet — see blockers in `broadcast-kit doctor`)'}")
    typer.echo("Next: see CATALOG.md Recipe E for the produce-publish flow.")
    return result
